# Generated by Django 4.0.3 on 2022-03-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Área')),
                ('nombre_abreviado', models.CharField(blank=True, max_length=20, verbose_name='Nombre Abreviado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Área')),
                ('nombre_abreviado', models.CharField(blank=True, max_length=20, verbose_name='Nombre Abreviado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.departamento')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
