# Generated by Django 4.0.3 on 2022-03-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='numero',
        ),
    ]
