# Generated by Django 4.0.3 on 2022-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='nombre_abreviado',
        ),
        migrations.AddField(
            model_name='departamento',
            name='domicilio',
            field=models.CharField(default=123, max_length=100, verbose_name='Domicilio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='email',
            field=models.EmailField(default=444, max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='telefono',
            field=models.PositiveIntegerField(default=111, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Departamento'),
        ),
    ]
