# Generated by Django 4.0.3 on 2022-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_alter_departamento_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='telefono_ext',
            field=models.PositiveIntegerField(default=3201),
        ),
    ]
