# Generated by Django 4.0.3 on 2022-03-10 15:30

from django.db import migrations


def create_data(apps, schema_editor):
    Area = apps.get_model('estructura', 'Area')
    Area(numero="01", nombre="Customer 001", nombre_abreviado="customer001@email.com", telefono_ext="3201", fecha_creacion= "2022-03-10", fecha_actualizacion= "2022-03-10").save()


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_area_telefono_ext'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]  
