# Generated by Django 4.0.3 on 2022-03-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_estructura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='departamento',
        ),
    ]
