# Generated by Django 4.0.2 on 2022-03-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_curso', models.CharField(max_length=100, verbose_name='Nombre Tipo Curso')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Tipo Curso',
                'verbose_name_plural': 'Tipo Curso',
                'ordering': ['-tipo_curso'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100, verbose_name='Nombre Curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de Finalización')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('cantidad_horas_catedra', models.IntegerField(default=0)),
                ('arancelado', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
