# Generated by Django 4.0.2 on 2022-03-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Área')),
                ('nombre_abreviado', models.CharField(blank=True, max_length=20, verbose_name='Nombre Abreviado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PersonalDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar de Nacimiento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('LC', 'Libreta Cívica'), ('PAS', 'Pasaporte')], default='DNI', max_length=3)),
                ('numero_documento', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta_docente.area')),
            ],
            options={
                'verbose_name': 'Personal Docente',
                'verbose_name_plural': 'Personal Docente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
