# Generated by Django 4.0.3 on 2022-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldocente',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
