# Generated by Django 4.0.3 on 2022-03-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0003_claustro_pesonal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pesonal',
            new_name='Personal',
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
    ]
