# Generated by Django 4.0.3 on 2022-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0004_rename_pesonal_personal_alter_personal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claustro',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Claustro'),
        ),
    ]
