# Generated by Django 4.0.3 on 2022-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0005_alter_claustro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='es_director',
            field=models.BooleanField(default=False),
        ),
    ]
