# Generated by Django 4.0.3 on 2022-03-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0007_departamento_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='es_director',
        ),
    ]
