# Generated by Django 4.0.3 on 2022-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0008_remove_personal_es_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cortesia',
            field=models.CharField(default='Sr/Sra', max_length=10, verbose_name='Título de Cortesía'),
        ),
    ]
