# Generated by Django 4.0.3 on 2022-03-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0009_personal_cortesia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDecano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=b'I00\n')),
                ('fecha_alta_cargo', models.DateField(verbose_name='Fecha que asume el cargo')),
                ('fecha_baja_cargo', models.DateField(verbose_name='Fecha que deja el cargo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('director_decano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta_docente.personal')),
            ],
            options={
                'verbose_name': 'Director Decano',
                'verbose_name_plural': 'Directores Decanos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
