# Generated by Django 4.0.3 on 2022-03-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0010_directordecano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directordecano',
            old_name='estado',
            new_name='es_activo',
        ),
    ]
