# Generated by Django 4.0.3 on 2022-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0012_alter_directordecano_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directordecano',
            name='fecha_baja_cargo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha que deja el cargo'),
        ),
    ]
