# Generated by Django 4.0.3 on 2022-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0013_alter_directordecano_fecha_baja_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directordecano',
            name='es_activo',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
