# Generated by Django 4.0.3 on 2022-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0017_alter_directordecano_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directordecano',
            name='es_activo',
            field=models.BooleanField(),
        ),
    ]
