# Generated by Django 4.0.3 on 2022-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0018_alter_directordecano_es_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Agrupamiento')),
            ],
            options={
                'verbose_name': 'Agrupamiento',
                'verbose_name_plural': 'Agrupamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='claustro',
            name='codigo',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
