# Generated by Django 4.0.3 on 2022-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0019_agrupamiento_claustro_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrupamiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Claustro', 'verbose_name_plural': 'Claustros'},
        ),
        migrations.RemoveField(
            model_name='claustro',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='agrupamiento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Claustro'),
        ),
    ]
