# Generated by Django 4.0.3 on 2022-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0020_alter_agrupamiento_options_remove_claustro_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrupamiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Agrupamiento', 'verbose_name_plural': 'Agrupamientos'},
        ),
        migrations.AlterField(
            model_name='agrupamiento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Agrupamiento'),
        ),
    ]
