# Generated by Django 4.0.3 on 2022-03-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_docente', '0021_alter_agrupamiento_options_alter_agrupamiento_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agrupamiento',
        ),
        migrations.DeleteModel(
            name='DirectorDecano',
        ),
    ]
